import { Chapter, Comic, Transaction } from "@/lib/types";

export const eventsData = [
  {
    id: 1,
    src: "/events/comic-con.jpg",
    alt: "Comic con",
    link: "https://www.straqa.events/nerdworkcomiccon",
    date: "September 6, 2025",
    title: "Comic Con 2025",
    subtitle:
      "Experience a day of creativity and connection at our annual community event! ",
  },
  {
    id: 2,
    src: "/events/tech-summit.jpg",
    alt: "tech summit",
    link: "",
    date: "May 21, 2025",
    title: "Tech Innovation Summit 2025",
    subtitle:
      "Join industry leaders to explore the latest in technology and innovation.",
  },
  {
    id: 3,
    src: "/events/arts-fair.jpg",
    alt: "arts fair",
    link: "",
    date: "June 10, 2025",
    title: "Arts & Crafts Fair 2025",
    subtitle: "Showcase your talents and discover new art at our annual fair!",
  },
];

export const comicData: Comic[] = [
  {
    id: 1,
    image: "/events/anime-con.jpg",
    title: "Mystic Chronicles: The Awakening",
    short_description: "Just a short description",
    status: "draft",
    chapters: 3,
    last_updated: "24/07/2024",
    genres: ["adventure", "fantasy", "historical"],
  },
  {
    id: 2,
    image: "/events/anime-con.jpg",
    title: "In My Head",
    short_description: "Just a short description",
    status: "draft",
    chapters: 3,
    last_updated: "24/07/2024",
    genres: ["sci-fi", "romance", "thriller", "historical"],
  },
  {
    id: 3,
    image: "/events/anime-con.jpg",
    title: "Totem: Vessel of the Gods",
    short_description: "Just a short description",
    status: "published",
    chapters: 3,
    last_updated: "24/07/2024",
    genres: ["adventure", "sci-fi", "thriller", "historical"],
  },
  {
    id: 4,
    image: "/events/anime-con.jpg",
    title: "Celestial Eyes",
    short_description: "Just a short description",
    status: "published",
    chapters: 3,
    last_updated: "24/07/2024",
    genres: ["adventure", "fantasy", "mystery", "sci-fi"],
    rating: "12 +",
  },
  {
    id: 5,
    image: "/events/anime-con.jpg",
    title: "This Side Up",
    short_description: "Just a short description",
    status: "scheduled",
    chapters: 3,
    last_updated: "24/07/2024",
    genres: ["adventure", "superhero", "historical"],
  },
  {
    id: 6,
    image: "/events/anime-con.jpg",
    title: "Dream",
    short_description: "Just a short description",
    status: "scheduled",
    chapters: 3,
    last_updated: "24/07/2024",
    genres: ["adventure", "mystery", "romance", "superhero"],
  },
  {
    id: 7,
    image: "/events/anime-con.jpg",
    title: "Shuri",
    short_description: "Just a short description",
    status: "upcoming",
    chapters: 3,
    last_updated: "24/07/2024",
    genres: ["thriller", "superhero", "historical"],
  },
  {
    id: 8,
    image: "/events/anime-con.jpg",
    title: "The Ambassadors",
    short_description: "Just a short description",
    status: "upcoming",
    chapters: 3,
    last_updated: "24/07/2024",
    genres: ["adventure", "mystery", "sci-fi"],
  },
];

export const creatorTransactions: Transaction[] = [
  {
    id: "1",
    type: "earning",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "2",
    type: "earning",
    status: "completed",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "3",
    type: "earning",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "4",
    type: "withdrawal",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "5",
    type: "withdrawal",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "6",
    type: "gift",
    status: "completed",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "7",
    type: "earning",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "8",
    type: "purchase",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "9",
    type: "earning",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "10",
    type: "withdrawal",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "11",
    type: "withdrawal",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "12",
    type: "withdrawal",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "13",
    type: "withdrawal",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
  {
    id: "14",
    type: "withdrawal",
    status: "pending",
    description: "m@example.com",
    amount: 50,
    date: "08/04/25",
  },
];

export const chapterData: Chapter[] = [
  {
    id: 1,
    image: "/events/anime-con.jpg",
    title: "Mystic Chronicles: The Awakening",
    description: "Just a short description",
    status: "draft",
    pages: 3,
    date: "24/07/2024",
    read: true,
    unlocked: true,
  },
  {
    id: 2,
    image: "/events/anime-con.jpg",
    title: "Mystic Chronicles: The Awakening",
    description: "Just a short description",
    status: "draft",
    pages: 3,
    date: "24/07/2024",
    read: true,
    unlocked: true,
  },
  {
    id: 3,
    image: "/events/anime-con.jpg",
    title: "Mystic Chronicles: The Awakening",
    description: "Just a short description",
    status: "published",
    pages: 3,
    date: "24/07/2024",
    read: false,
    unlocked: false,
  },
  {
    id: 4,
    image: "/events/anime-con.jpg",
    title: "Mystic Chronicles: The Awakening",
    description: "Just a short description",
    status: "published",
    pages: 3,
    date: "24/07/2024",
    read: false,
    unlocked: false,
  },
  {
    id: 5,
    image: "/events/anime-con.jpg",
    title: "Mystic Chronicles: The Awakening",
    description: "Just a short description",
    status: "scheduled",
    pages: 3,
    date: "24/07/2024",
    read: false,
    unlocked: false,
  },
  {
    id: 6,
    image: "/events/anime-con.jpg",
    title: "Mystic Chronicles: The Awakening",
    description: "Just a short description",
    status: "scheduled",
    pages: 3,
    date: "24/07/2024",
    read: false,
    unlocked: false,
  },
  {
    id: 7,
    image: "/events/anime-con.jpg",
    title: "Mystic Chronicles: The Awakening",
    description: "Just a short description",
    status: "scheduled",
    pages: 3,
    date: "24/07/2024",
    read: false,
    unlocked: false,
  },
  {
    id: 8,
    image: "/events/anime-con.jpg",
    title: "Mystic Chronicles: The Awakening",
    description: "Just a short description",
    status: "published",
    pages: 3,
    date: "24/07/2024",
    read: false,
    unlocked: false,
  },
];
